---
- name: Install dependancies
  apt: pkg={{ item }} state=installed update_cache=no
  with_items:
    - python

- name: destination location exists
  action: file path=/home/pi/gwe state=directory owner=pi group=pi mode=0755

- name: Download GWE v1.5.23
  get_url:
      url: https://s3-us-west-2.amazonaws.com/exosite-client-downloads/gateway-engine-release-area/gmq-master/GatewayEngine.v1.5.23.tar.gz
      dest: /home/pi/gwe
      checksum: sha256:78d8600ab4c2f9061c82e1523019155a96620af5db2af1f7f3b8edd9ea12949a

- name: Unpack it
  unarchive:
      remote_src: yes
      src: /home/pi/gwe/GatewayEngine.v1.5.23.tar.gz
      dest: /home/pi/gwe

- name: Install GWE
  args:
      chdir: /home/pi/gwe/gateway-engine
      creates: /usr/local/bin/gwe
  command: ./install.sh

- name: Get current GWE config
  command: gwe --gateway-cfg
  register: gwe_cfg

- name: Set GWE ID to MAC
  command: gwe --set-iface eth0 -d DEBUG
  when: "'iface = eth0' not in gwe_cfg.stdout"

- name: Set Product ID
  command: gwe --set-product-id {{ product_id }}
  when: "'model = \'\'' in gwe_cfg.stdout or 'vendor = \'\'' in gwe_cfg.stdout"

- name: Set GWE Host
  command: gdc cfg set device host m2.exosite.io -f gwe
  when: "'host = m2.exosite.io' not in gwe_cfg.stdout"

- name: Startup GWE without a reboot.
  systemd:
      name: supervisor.service
      state: started
      enabled: True

