#!/usr/bin/env bash
docker run --rm -it \
  -v /run/host-services/ssh-auth.sock:/ssh-agent \
  -e SSH_AUTH_SOCK="/ssh-agent" \
  -v $(pwd):/ansible_playbooks \
  -w /ansible_playbooks \
  -v /var/log/ansible/ansible.log \
  local/ansible-playbook "$@"
