---
- hosts: BBW
  become: yes
  vars:
    serial_ports: BB-UART1,BB-UART2
  roles:
  - debian
  - mosquitto
  - nodered

  # These should move into a role. Maybe debian?
  tasks:
  - name: Disable unwanted BeagleBone services
    service: name={{ item }} state=stopped enabled=no
    with_items:
      - cloud9.socket
      - cloud9.service
      - bonescript.socket
      - bonescript.service
      - bonescript-autorun.service
      - apache2.service
    when: hardware_class == "beaglebone"

  - name: Setup serial ports to be availible on reboot
    lineinfile:
      path: /etc/default/capemgr
      line: "CAPE={{ serial_ports }}"
      regexp: '^CAPE='
    when: hardware_class == "beaglebone"

  - name: Stop WiFi when no hardware
    service: name={{ item }} state=stopped enabled=no
    with_items:
      - wpa_supplicant
    when: hardware_sub == "white"


#  vim: set et sw=2 ts=2 :
