---
- name: install debian packages
  apt:
    state: present
    update_cache: yes
    pkg:
      - acl # Ansible uses setfacl
      - git
      - build-essential
      - python-pip
      - ruby-dev
      - python-dev
      - vim
      - curl
      - locales
      - ntpdate
      - avahi-utils
      - python

- name: Pi specific packages
  when: hardware_class == "raspberrypi"
  apt:
    state: present
    pkg:
      - wiringpi

