---
- name: install debian packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - git
    - build-essential
    - python-pip
    - ruby-dev
    - python-dev
    - vim
    - curl
    - locales
    - ntpdate
    - avahi-utils
    - python

- name: Pi specific packages
  when: hardware_class == "raspberrypi"
  apt: pkg={{ item }} state=installed
  with_items:
    - wiringpi

