---
- name: Install packages
  apt:
    pkg:
      - etherpuppet
      - horst
      - ostinato
      - packeth
      - pcapfix
      - tcpdump
      - tcpxtract
      - tshark
      - wireshark-qt


...

