---
- name: Add TimescaleDB repos
  apt_repository:
      repo: 'ppa:timescale/timescaledb-ppa'

- name: Install TimescaleDB
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - timescaledb
      # other postgres tools?
      # postgis ?

